version: 0.2

phases:
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install awscli python-dotenv

  build:
    commands:
      - pip install -e .[cfn]
      - make package

cache:
  paths:
    /root/.cache/pip

artifacts:
    files:
      - cloudformation/template.yaml
      - cloudformation/template-config.json
      - cloudformation/service-config.json
